name: Update Changelog

on:
  push:
    branches: [ main, master ]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.token }}
      
      - name: Generate changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.token }}
          output-file: 'CHANGELOG.md'
          version-file: 'package.json'
          skip-on-empty: 'false'
